# 1. 라이브러리 호출

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim


# 2. 모델 정의

In [3]:
class SimpleNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 예제 모델 초기화
input_dim = 3
hidden_dim = 5
output_dim = 2

model = SimpleNet(input_dim, hidden_dim, output_dim)


# 3. 데이터 준비

In [4]:
# 임의의 입력 데이터 생성
x = torch.rand((10, input_dim))
print("\nInput Data:")
print(x)

# 예측 실행
y_pred = model(x)
print("\nInitial Predictions:")
print(y_pred)



Input Data:
tensor([[0.5354, 0.9236, 0.5187],
        [0.1560, 0.5763, 0.7143],
        [0.8691, 0.8404, 0.8317],
        [0.2344, 0.9837, 0.2160],
        [0.6203, 0.8891, 0.0080],
        [0.3176, 0.9639, 0.0176],
        [0.6478, 0.4594, 0.9892],
        [0.9604, 0.5049, 0.1305],
        [0.2309, 0.6301, 0.9132],
        [0.2822, 0.5757, 0.1026]])

Initial Predictions:
tensor([[0.1312, 0.2406],
        [0.1444, 0.2459],
        [0.1343, 0.2419],
        [0.1291, 0.2398],
        [0.1362, 0.2426],
        [0.1316, 0.2408],
        [0.1499, 0.2482],
        [0.1542, 0.2499],
        [0.1410, 0.2446],
        [0.1486, 0.2477]], grad_fn=<AddmmBackward0>)


# 4. 손실 함수 및 옵티마이저 정의

In [5]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)


# 5. 학습

**임의 데이터 사용**

In [6]:
# 임의의 타겟 데이터 생성
y_target = torch.rand((10, output_dim))
print("\nTarget Data:")
print(y_target)

# 학습 과정
num_epochs = 100
for epoch in range(num_epochs):
    # 예측
    y_pred = model(x)

    # 손실 계산
    loss = criterion(y_pred, y_target)

    # 역전파 및 최적화
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # 10 에폭마다 손실 출력
    if (epoch+1) % 10 == 0:
        print(f"\nEpoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")



Target Data:
tensor([[0.9312, 0.7778],
        [0.7259, 0.2668],
        [0.2635, 0.4606],
        [0.3458, 0.7771],
        [0.2982, 0.4637],
        [0.7144, 0.3102],
        [0.2468, 0.4384],
        [0.1175, 0.2678],
        [0.9390, 0.4425],
        [0.1022, 0.3457]])

Epoch [10/100], Loss: 0.1277

Epoch [20/100], Loss: 0.1155

Epoch [30/100], Loss: 0.1057

Epoch [40/100], Loss: 0.0977

Epoch [50/100], Loss: 0.0913

Epoch [60/100], Loss: 0.0861

Epoch [70/100], Loss: 0.0820

Epoch [80/100], Loss: 0.0786

Epoch [90/100], Loss: 0.0759

Epoch [100/100], Loss: 0.0737


# 6. 최종 예측 확인

In [7]:
print("\nFinal Predictions after Training:")
print(model(x))



Final Predictions after Training:
tensor([[0.3509, 0.3792],
        [0.3632, 0.3844],
        [0.3562, 0.3814],
        [0.3469, 0.3775],
        [0.3540, 0.3805],
        [0.3487, 0.3783],
        [0.3711, 0.3877],
        [0.3728, 0.3885],
        [0.3610, 0.3835],
        [0.3653, 0.3853]], grad_fn=<AddmmBackward0>)
